version: '3'

services:
  # Database
  db:
    image: mysql:5.7.44
    volumes:
      - 'db_data:/var/lib/mysql'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${Password}"
      MYSQL_DATABASE: "${Database}"
      MYSQL_USER: "${User}"
      MYSQL_PASSWORD: "${Password}"
    networks:
      - "${Network}"
  #phpadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8004:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${Password}"
    networks:
      - "${Network}"
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8008:80'
    restart: always
    volumes:
      - './:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: "${Database}"
      WORDPRESS_DB_USER: "${User}"
      WORDPRESS_DB_PASSWORD: "${Password}"
    networks:
      - "${Network}"

networks:
  mywebsite:

volumes:
  db_data:
